name: PDF to Image Upload
code: pdf-to-image-upload
version: 0.1.0
readme: README.md
description: This is PDF to Image Upload plugin
category: upload
package_manager: pip
actions:
  upload:
    entrypoint: plugin.upload.Uploader
    options: null
    supported_data_type: image
    excel_config:
      max_file_size_mb: 10
      max_rows: 100000
      max_columns: 50
    ui_schema:
